name: Debug GCP SA Key

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest


    steps:

      - name: Output first 40 characters of the secret
        run: |
          echo "START OF SECRET:"
          echo "${{ secrets.GCP_HOMEPAGE_SA_KEY }}" | head -c 40 || echo "SECRET EMPTY"
          echo -e "\nEND OF SECRET"

      - name: Save secret to file
        run: echo "${{ secrets.GCP_HOMEPAGE_SA_KEY }}" > sa-key.json

      - name: Print first 10 lines of key file
        run: head -n 10 sa-key.json || echo "No key written"

      - name: Try to activate service account
        run: |
          gcloud auth activate-service-account --key-file=sa-key.json || echo "Activation failed"

      - name: Check gcloud project (if auth succeeded)
        run: gcloud config list
